# Generated by Django 6.0.4 on 2026-04-24 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_projectsection_description_projectsection_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('prod', 'Production'), ('dev', 'Development')], db_index=True, max_length=4)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Импортированное изменение',
                'verbose_name_plural': 'Импортированные изменения',
                'ordering': ['-date', 'source'],
            },
        ),
        migrations.DeleteModel(
            name='TagUpdate',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectsection',
            options={'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['number'], 'verbose_name_plural': 'Релизы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['text'], 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['project'], 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['title'], 'verbose_name_plural': 'Обновления'},
        ),
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='updates', to='support.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='release',
            name='real_release_date',
            field=models.DateField(verbose_name='Фактическая дата выхода'),
        ),
    ]
